
InstanceSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupDescription: Enable SSH access via port 22
    SecurityGroupIngress:
      # finance team network
      - CidrIp: 10.0.48.0/24
        FromPort: 20
        IpProtocol: tcp
        ToPort: 22
        CidrIp: 10.0.112.0/24
       # marketing team network
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        # application team support network
      - CidrIp: 10.0.176.0/24
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22


Output: 
  StackSSHSecurityGroup: # define this output to return the sg ID
    Description: The SSH Security Group for our Company
    Value: !Ref MyComaoyWideSSHSecurityGroup
